- hosts: all
  gather_facts: false
  ignore_unreachable: true
  tasks:
    - name: Read disk usage
      ansible.builtin.command: df -h
      register: disk_usage
      changed_when: false

    - name: Show disk usage
      ansible.builtin.debug:
        msg: "{{ disk_usage.stdout_lines }}"
